import { Product } from "@/commons/types/product";
import { AppImages } from "../../public/images/images";
import { Collection } from "@/commons/types/collection";
import {
  ProductCategory,
  ProductSeason,
  ProductColor,
  ProductPlantType,
  ProductType,
} from "@/commons/constants";

export const dummyProductData: Product[] = [
  {
    id: "1",
    name: "Aloe Vera",
    shortDescription: "Soothing succulent plant",
    price: 19.99,
    originalPrice: 24.99,
    discountPercentage: 20,
    rating: 4.7,
    reviews: 210,
    imageUrls: [
      AppImages.plantImg1,
      AppImages.plantImg2,
      AppImages.plantImg3,
      AppImages.plantImg4,
    ],
    inStock: true,
    category: ProductCategory.IndoorPlants,
    season: ProductSeason.Summer,
    color: ProductColor.LightGreen,
    plantType: ProductPlantType.CactiAndSucculents,
    productType: ProductType.Plant,
    description:
      "Aloe Vera is known for its medicinal and skin-soothing properties.",
    isBestSeller: false,
    isTrending: false,
    createdAt: new Date("2024-01-10T08:45:00Z"),
  },
  {
    id: "2",
    name: "Snake Plant",
    shortDescription: "Low-maintenance air purifier",
    price: 24.99,
    originalPrice: 29.99,
    discountPercentage: 15,
    rating: 4.8,
    reviews: 180,
    imageUrls: [
      AppImages.plantImg2,
      AppImages.plantImg2,
      AppImages.plantImg2,
      AppImages.plantImg2,
    ],
    inStock: true,
    category: ProductCategory.IndoorPlants,
    season: ProductSeason.Winter,
    color: ProductColor.DarkGreen,
    plantType: ProductPlantType.LowLightPlants,
    productType: ProductType.Plant,
    isBestSeller: false,
    isTrending: false,
    description: "Perfect for beginners and excellent air purifier.",
    createdAt: new Date("2025-02-02T12:30:00Z"),
  },
  {
    id: "3",
    name: "Monstera Deliciosa",
    shortDescription: "Swiss Cheese Plant",
    price: 39.99,
    originalPrice: 49.99,
    discountPercentage: 20,
    rating: 4.9,
    reviews: 250,
    imageUrls: [
      AppImages.plantImg3,
      AppImages.plantImg3,
      AppImages.plantImg3,
      AppImages.plantImg3,
    ],
    inStock: true,
    category: ProductCategory.IndoorPlants,
    season: ProductSeason.Spring,
    color: ProductColor.DarkGreen,
    plantType: ProductPlantType.AirPurifyingPlants,
    productType: ProductType.Plant,
    isBestSeller: false,
    isTrending: false,
    description: "Stunning tropical plant with unique leaf patterns.",
    createdAt: new Date("2023-12-20T14:10:00Z"),
  },
  {
    id: "4",
    name: "English Ivy",
    shortDescription: "Classic hanging plant",
    price: 15.99,
    originalPrice: 19.99,
    discountPercentage: 20,
    rating: 4.5,
    reviews: 150,
    imageUrls: [
      AppImages.plantImg4,
      AppImages.plantImg4,
      AppImages.plantImg4,
      AppImages.plantImg4,
    ],
    inStock: false,
    category: ProductCategory.IndoorPlants,
    season: ProductSeason.Spring,
    color: ProductColor.LightGreen,
    plantType: ProductPlantType.HangingPlants,
    productType: ProductType.Plant,
    isBestSeller: false,
    isTrending: false,
    description: "Elegant trailing vine perfect for hanging baskets.",
    createdAt: new Date("2024-01-05T09:15:00Z"),
  },
  {
    id: "5",
    name: "Lavender",
    shortDescription: "Fragrant herb plant",
    price: 17.99,
    originalPrice: 22.99,
    discountPercentage: 22,
    rating: 4.6,
    reviews: 190,
    imageUrls: [
      AppImages.plantImg1,
      AppImages.plantImg1,
      AppImages.plantImg1,
      AppImages.plantImg1,
    ],
    inStock: true,
    category: ProductCategory.OutdoorPlants,
    season: ProductSeason.Summer,
    color: ProductColor.Gray,
    plantType: ProductPlantType.AromaticPlants,
    productType: ProductType.Plant,
    isBestSeller: false,
    isTrending: false,
    description: "Beautiful aromatic plant with calming properties.",
    createdAt: new Date("2024-12-31T16:50:00Z"),
  },
  {
    id: "6",
    name: "Cactus Collection",
    shortDescription: "Mixed cactus varieties",
    price: 29.99,
    originalPrice: 34.99,
    discountPercentage: 15,
    rating: 4.7,
    reviews: 120,
    imageUrls: [
      AppImages.plantImg2,
      AppImages.plantImg2,
      AppImages.plantImg2,
      AppImages.plantImg2,
    ],
    inStock: true,
    category: ProductCategory.OutdoorPlants,
    season: ProductSeason.Summer,
    color: ProductColor.Gray,
    plantType: ProductPlantType.CactiAndSucculents,
    productType: ProductType.Plant,
    isBestSeller: false,
    isTrending: false,
    description: "Collection of drought-resistant desert cacti.",
    createdAt: new Date("2023-12-30T16:50:00Z"),
  },
  {
    id: "7",
    name: "Peace Lily",
    shortDescription: "Air-purifying beauty",
    price: 27.99,
    originalPrice: 32.99,
    discountPercentage: 15,
    rating: 4.8,
    reviews: 220,
    imageUrls: [
      AppImages.plantImg3,
      AppImages.plantImg3,
      AppImages.plantImg3,
      AppImages.plantImg3,
    ],
    inStock: true,
    category: ProductCategory.IndoorPlants,
    season: ProductSeason.Spring,
    color: ProductColor.DarkGreen,
    plantType: ProductPlantType.FloweringPlants,
    productType: ProductType.Plant,
    isBestSeller: false,
    isTrending: false,
    description: "Elegant flowering plant that helps clean indoor air.",
    createdAt: new Date("2024-11-5T16:50:00Z"),
  },
  {
    id: "8",
    name: "Rosemary",
    shortDescription: "Culinary herb plant",
    price: 14.99,
    originalPrice: 19.99,
    discountPercentage: 25,
    rating: 4.6,
    reviews: 170,
    imageUrls: [
      AppImages.plantImg4,
      AppImages.plantImg4,
      AppImages.plantImg4,
      AppImages.plantImg4,
    ],
    inStock: true,
    category: ProductCategory.OutdoorPlants,
    season: ProductSeason.Spring,
    color: ProductColor.DarkGreen,
    plantType: ProductPlantType.AromaticPlants,
    productType: ProductType.Plant,
    isBestSeller: false,
    isTrending: false,
    createdAt: new Date("2025-1-5T16:50:00Z"),
    description: "Fragrant herb perfect for cooking and gardens.",
  },

  {
    id: "b1",
    name: "Golden Pothos",
    shortDescription: "Easy-care trailing plant",
    price: 24.99,
    originalPrice: 34.99,
    discountPercentage: 29,
    rating: 4.9,
    reviews: 423,
    imageUrls: [
      AppImages.plantImg5,
      AppImages.plantImg5,
      AppImages.plantImg5,
      AppImages.plantImg5,
    ],
    isBestSeller: true,
    isTrending: false,
    inStock: true,
    category: ProductCategory.IndoorPlants,
    season: ProductSeason.Spring,
    color: ProductColor.LightGreen,
    plantType: ProductPlantType.HangingPlants,
    productType: ProductType.Plant,
    createdAt: new Date("2025-1-2T16:50:00Z"),
    description: "Easy-care trailing plant with heart-shaped leaves.",
  },
  {
    id: "b2",
    name: "Chinese Evergreen",
    shortDescription: "Beautiful foliage plant",
    price: 39.99,
    originalPrice: 49.99,
    discountPercentage: 20,
    rating: 4.7,
    reviews: 289,
    imageUrls: [
      AppImages.plantImg6,
      AppImages.plantImg6,
      AppImages.plantImg6,
      AppImages.plantImg6,
    ],
    isBestSeller: true,
    isTrending: false,
    inStock: true,
    category: ProductCategory.IndoorPlants,
    season: ProductSeason.Winter,
    color: ProductColor.Gray,
    plantType: ProductPlantType.AirPurifyingPlants,
    productType: ProductType.Plant,
    createdAt: new Date("2025-1-29T16:50:00Z"),
    description: "Beautiful foliage plant that tolerates low light conditions.",
  },
  {
    id: "b3",
    name: "ZZ Plant",
    shortDescription: "Nearly indestructible plant",
    price: 44.99,
    originalPrice: 54.99,
    discountPercentage: 18,
    rating: 4.8,
    reviews: 356,
    imageUrls: [
      AppImages.plantImg7,
      AppImages.plantImg7,
      AppImages.plantImg7,
      AppImages.plantImg7,
    ],
    isBestSeller: true,
    isTrending: false,
    inStock: true,
    category: ProductCategory.IndoorPlants,
    season: ProductSeason.Autumn,
    color: ProductColor.DarkGreen,
    plantType: ProductPlantType.DroughtResistant,
    productType: ProductType.Plant,
    createdAt: new Date("2024-12-28T16:50:00Z"),
    description: "Nearly indestructible plant with glossy leaves.",
  },
  {
    id: "b4",
    name: "Spider Plant",
    shortDescription: "Classic hanging plant",
    price: 19.99,
    originalPrice: 29.99,
    discountPercentage: 33,
    rating: 4.6,
    reviews: 278,
    imageUrls: [
      AppImages.plantImg1,
      AppImages.plantImg1,
      AppImages.plantImg1,
      AppImages.plantImg1,
    ],
    isBestSeller: true,
    isTrending: true,
    inStock: true,
    category: ProductCategory.IndoorPlants,
    season: ProductSeason.Spring,
    color: ProductColor.LightGreen,
    plantType: ProductPlantType.AirPurifyingPlants,
    productType: ProductType.Plant,
    createdAt: new Date("2025-1-15T16:50:00Z"),
    description: "Classic hanging plant that produces many babies.",
  },

  {
    id: "t1",
    name: "Golden Pothos",
    shortDescription: "Easy-care trailing plant",
    price: 24.99,
    originalPrice: 34.99,
    discountPercentage: 29,
    rating: 4.9,
    reviews: 423,
    imageUrls: [
      AppImages.plantImg5,
      AppImages.plantImg5,
      AppImages.plantImg5,
      AppImages.plantImg5,
    ],
    isBestSeller: true,
    isTrending: true,
    inStock: true,
    category: ProductCategory.IndoorPlants,
    season: ProductSeason.Spring,
    color: ProductColor.LightGreen,
    plantType: ProductPlantType.HangingPlants,
    productType: ProductType.Plant,
    createdAt: new Date("2024-12-25T16:50:00Z"),
    description: "Easy-care trailing plant with heart-shaped leaves.",
  },
  {
    id: "t2",
    name: "Chinese Evergreen",
    shortDescription: "Beautiful foliage plant",
    price: 39.99,
    originalPrice: 49.99,
    discountPercentage: 20,
    rating: 4.7,
    reviews: 289,
    imageUrls: [
      AppImages.plantImg6,
      AppImages.plantImg6,
      AppImages.plantImg6,
      AppImages.plantImg6,
    ],
    isBestSeller: true,
    isTrending: true,

    inStock: true,
    category: ProductCategory.IndoorPlants,
    season: ProductSeason.Winter,
    color: ProductColor.Gray,
    plantType: ProductPlantType.AirPurifyingPlants,
    productType: ProductType.Plant,
    createdAt: new Date("2025-1-20T16:50:00Z"),
    description: "Beautiful foliage plant that tolerates low light conditions.",
  },
  {
    id: "t3",
    name: "ZZ Plant",
    shortDescription: "Nearly indestructible plant",
    price: 44.99,
    originalPrice: 54.99,
    discountPercentage: 18,
    rating: 4.8,
    reviews: 356,
    imageUrls: [
      AppImages.plantImg7,
      AppImages.plantImg7,
      AppImages.plantImg7,
      AppImages.plantImg7,
    ],
    isBestSeller: false,
    isTrending: true,

    inStock: true,
    category: ProductCategory.IndoorPlants,
    season: ProductSeason.Autumn,
    color: ProductColor.DarkGreen,
    plantType: ProductPlantType.DroughtResistant,
    productType: ProductType.Plant,
    createdAt: new Date("2025-2-3T16:50:00Z"),
    description: "Nearly indestructible plant with glossy leaves.",
  },
  {
    id: "t4",
    name: "Spider Plant",
    shortDescription: "Classic hanging plant",
    price: 19.99,
    originalPrice: 29.99,
    discountPercentage: 33,
    rating: 4.6,
    reviews: 278,
    imageUrls: [
      AppImages.plantImg1,
      AppImages.plantImg1,
      AppImages.plantImg1,
      AppImages.plantImg1,
    ],
    isBestSeller: false,
    isTrending: true,

    inStock: true,
    category: ProductCategory.IndoorPlants,
    season: ProductSeason.Spring,
    color: ProductColor.LightGreen,
    plantType: ProductPlantType.AirPurifyingPlants,
    productType: ProductType.Plant,
    createdAt: new Date("2025-1-25T16:50:00Z"),
    description: "Classic hanging plant that produces many babies.",
  },
];

export const collections: Collection[] = [
  {
    id: "1",
    title: "Indoor Plants",
    slug: "indoor-plants",
    imageUrl: AppImages.plantImg1,
    productCount: 48,
    featured: true,
  },
  {
    id: "2",
    title: "Pots & Planters",
    slug: "pots-planters",
    imageUrl: AppImages.plantImg1,
    productCount: 36,
    featured: true,
  },
  {
    id: "3",
    title: "Outdoor Plants",
    slug: "outdoor-plants",
    imageUrl: AppImages.plantImg1,
    productCount: 42,
    featured: true,
  },
  {
    id: "4",
    title: "Indoor Plants",
    slug: "indoor-plants",
    imageUrl: AppImages.plantImg1,
    productCount: 48,
    featured: true,
  },
];
