// src/app/layout.tsx
"use client";

// import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Outfit } from "next/font/google";
import { ReduxProvider } from "@/providers/ReduxProvider";
import { useStorePersist } from "@/hooks/useStorePersist";

function StoreInitializer() {
  useStorePersist();
  return null;
}

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Include the weights you need
  variable: "--font-outfit", // Optional: if you want to use it as a CSS variable
});

// export const metadata: Metadata = {
//   title: "EMadhyam",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased`}>
        <ReduxProvider>
          <StoreInitializer />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
